###
GET http://localhost:8080/api/employee
###
POST http://localhost:8080//api/employee
Content-Type: application/json

{
  "name": "Max2",
  "role": "Evil dictator2"
}

###
POST http://localhost:8080/api/manager?managersName=Max Super Evil Manager


###
GET http://localhost:8080/api/manager

###
DELETE http://localhost:8080/api/employee/9

###
PUT http://localhost:8080/api/employee/8
Content-Type: application/json

{
  "name": "Max1",
  "role": "Evil dictator2"
}